---
stages:
 - build
 - release

variables:
  IMAGE_LABELS: >
    --label vcs-url=$CI_PROJECT_URL
    --label com.skypicker.gitlab.ci.builder=$GITLAB_USER_EMAIL
    --label com.skypicker.gitlab.ci.pipeline=$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID
    --label com.skypicker.gitlab.ci.ref=$CI_BUILD_REF_NAME
    --label com.skypicker.gitlab.ci.build=$CI_PROJECT_URL/builds/$CI_BUILD_ID

before_script:
 - export CI_BUILD_REF_SLUG=${CI_BUILD_REF_NAME/\//-}

static-analysis:
  stage: build
  image: coala/base:0.8
  script:
   - coala-ci

build:
  stage: build
  image: docker:1.12
  script:
   - >
    docker build .
    --label build-date=`date -Iseconds`
    $IMAGE_LABELS
    --tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    --tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_SLUG
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
   - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_SLUG

release-tag:
  stage: release
  image: docker:1.12
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
   - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
   - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
   - tags

release-latest:
  stage: release
  image: docker:1.12
  script:
   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
   - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF
   - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF $CI_REGISTRY_IMAGE:latest
   - docker push $CI_REGISTRY_IMAGE:latest
  only:
   - master
